Summary page
daleinen7/bearcabulary pull request #26
Opened 2021-08-04 22:22 UTC by kndshein

2021-08-05 01:39 UTC, daleinen7 requested changes
Unhappiness ensues. 

<img width="1325" alt="Screen Shot 2021-08-04 at 8 39 19 PM" src="https://user-images.githubusercontent.com/6326891/128277515-7918497b-3d38-49fe-9742-c0b71a9c1db9.png">

2021-08-05 21:23 UTC, kndshein commented on src/pages/summary.jsx
> +  console.log(location);
Done.

2021-08-05 21:23 UTC, kndshein commented on src/pages/summary.jsx
> +              return <div key={index2}>{error}</div>;
Done.

2021-08-07 16:44 UTC, daleinen7 approved these changes
First coffee review from phone.

2021-08-07 16:44 UTC, merged