About
daleinen7/bearcabulary pull request #45
Opened 2021-08-30 14:07 UTC by daleinen7

2021-08-31 15:19 UTC, kndshein commented on src/components/Hero/hero.module.scss
> +.grid {
Naming it grid only to make it flex. *gasp*

2021-08-31 19:28 UTC, kndshein requested changes

2021-09-01 02:01 UTC, daleinen7 commented on src/components/Hero/index.jsx
> +const alphabet = [
Got it. It was a mix of our two predicted outcomes.

2021-09-01 05:10 UTC, kndshein approved these changes

2021-09-01 05:10 UTC, merged